# Generated by Django 6.0.1 on 2026-01-21 05:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarterLogs',
            new_name='BarterLog',
        ),
    ]
