# Generated by Django 6.0.1 on 2026-01-21 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_rename_barterlogs_barterlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AlterField(
            model_name='barterlog',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='barter.item'),
        ),
    ]
