# Generated by Django 6.0.1 on 2026-01-21 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0003_remove_item_status_alter_barterlog_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barterlog',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barterlog_set', to='barter.item'),
        ),
    ]
