# Generated by Django 6.0.1 on 2026-01-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0006_alter_wishlist_user_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'NEW'), ('Used', 'USED')], default='Used', max_length=20),
        ),
    ]
