# Generated by Django 6.0.1 on 2026-01-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0007_item_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
