# Generated by Django 6.0.1 on 2026-01-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0008_item_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='item_list',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
