# Generated by Django 6.0.1 on 2026-01-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0009_alter_wishlist_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image_url',
            field=models.URLField(),
        ),
    ]
