# Generated by Django 6.0.1 on 2026-01-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
