# Generated by Django 6.0.1 on 2026-01-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_image_url_delete_userimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image_url',
            new_name='img',
        ),
    ]
